spring:
  datasource:
    url: jdbc:mysql://localhost/users
    username: root
    password: secret
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
graphql:
  spqr:
    gui:
      enabled: true